# -------------------------------------------------------------------------------
# Globals parameters
# -------------------------------------------------------------------------------

# MANDATORY
CERT_PATH: '../PowerOps-Cert/'
NSX_MGR_IP: "10.215.66.53" 
OUTPUT_PATH: '../PowerOps-Docs/'
PREFIX_FOLDER: 'POps_doc_'

# OPTIONAL
#MENU: [ 1, 3, 2 ] #EXAMPLE
#MENU: [ [ 1, 3, 3 ], [ 1, 3, 2 ] ] #EXAMPLE
OUTPUT_FORMAT: 'CSV' #Possible values => {XLSX, CSV, YAML, JSON} / default = XLSX
