# -------------------------------------------------------------------------------
# Globals parameters
# -------------------------------------------------------------------------------

# MANDATORY
# CERT_PATH: /home/powerops/cert
# NSX_MGR_IP: "a.b.c.d" 
# OUTPUT_PATH: '/home/powerops/powerops_documentation/'
CERT_PATH: ./cert
NSX_MGR_IP: "10.123.16.36:8443" 
OUTPUT_PATH: './powerops_documentation/'
PREFIX_FOLDER: 'POps_doc_'

# OPTIONAL
#MENU: [ 1, 3, 2 ] #EXAMPLE
#MENU: [ [ 1, 3, 3 ], [ 1, 3, 2 ] ] #EXAMPLE
OUTPUT_FORMAT: 'CSV' #Possible values => {XSLX, CSV, YAML, JSON} / default = XLSX